spring:
  application:
    name: thProject
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: THPROJECT
    password: THPROJECT
    driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  port: 80

mybatis:
  configuration: 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit: DEBUG